name: gatepassx
description: "DePass - Dinner & Event Gate Pass Scanner and QR Generator"
publish_to: 'none'

version: 23.1.0+24

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  crypto: ^3.0.3
  qr_flutter: ^4.1.0
  share_plus: ^12.0.2
  path_provider: ^2.1.6
  intl: ^0.20.2
  file_picker: ^11.0.2
  shared_preferences: ^2.5.5
  mobile_scanner: ^7.2.0
  google_fonts: ^8.1.0
  dynamic_color: ^1.7.0
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/beep.wav
    - assets/icons/logo.svg
